# Generated by Django 2.2.5 on 2020-08-30 00:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Centro de Custo')),
                ('name_department', models.CharField(max_length=60, verbose_name='Departamento')),
                ('responsible', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centro de Custos',
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('identifier', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(1)], verbose_name='Registro')),
                ('name', models.CharField(max_length=130, verbose_name='Nome Funcionário')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
                ('admission', models.DateTimeField(verbose_name='Admissão')),
                ('resignation', models.DateTimeField(blank=True, null=True, verbose_name='Demissão')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aniversário')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, error_messages={'required': 'Porfavor digite seu e-mail.', 'unique': 'Já existe esse e-mail cadastrado.'}, max_length=70, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('role', models.CharField(max_length=60, verbose_name='Cargo')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('G', 'Masculino')], max_length=12, verbose_name='Gênero')),
                ('photo', stdimage.models.StdImageField(default='0000.jpg', upload_to='FotosFuncionarios')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.CostCenter', verbose_name='Centro de Custo')),
                ('unity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='users.Unity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
