# Generated by Django 2.2.5 on 2020-09-03 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200903_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='unity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='users.Unity'),
        ),
    ]
