# Generated by Django 2.2.5 on 2020-09-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200909_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
    ]
