# Generated by Django 2.2.5 on 2020-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200911_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, max_length=200, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identifier',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
