# Generated by Django 2.2.5 on 2020-11-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201024_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcenter',
            name='active',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='created',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='active',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='unity',
            name='modified',
        ),
    ]
