import csv
from django.db import migrations
from django.contrib.auth.models import User
from users.models import CostCenter


def insert_user_models(apps, schema_editor):
     with open("dados_importados/userOficial.CSV", "r+") as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=';')
        next(csv_reader)
        for row  in csv_reader:
            print(row)
            try:
                obj = User.objects.create(
                    username=row[0],
                    email=row[1],
                    password=row[2],
                    first_name=row[3],
                    last_name=row[4])
                obj.save()
            except User.DoesNotExist:
                print("Objeto não existe.")

def insert_costcenter_models(apps, schema_editor):
    with open("dados_importados/cost_center.CSV", "r+") as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        next(csv_reader)
        for row  in csv_reader:
            print(row)
            try:
                obj = CostCenter.objects.create(
                    number=row[0],
                    name_department=row[1],
                    responsible=row[2])
                obj.save()
            except CostCenter.DoesNotExist:
                print("Objeto não existe.")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201111_2258'),
    ]

    operations = [
        migrations.RunPython(insert_user_models),
        migrations.RunPython(insert_costcenter_models),
    ]




# # Generated by Django 2.2.5 on 2020-11-12 23:44
# import csv
# import random
# from django.db import migrations
# from django.contrib.auth.models import User
# from users.models import Unity, Employee, CostCenter


# def insert_unity_models(apps, schema_editor):
#     with open("dados_importados/unity.CSV", "r+") as csv_file:
#         csv_reader = csv.reader(csv_file, delimiter=';')
#         next(csv_reader)
#         for row  in csv_reader:
#             print(row)
#             try:
#                 obj = Unity.objects.create(
#                     id=row[0],
#                     name=row[1])
#                 obj.save()
#             except Unity.DoesNotExist:
#                 print("Objeto não existe.")


# def insert_employee_models(apps, schema_editor):
#     with open("dados_importados/funcionarios.csv", "r+") as csv_file:
#         csv_reader = csv.reader(csv_file, delimiter=',')
#         next(csv_reader)
#         for row  in csv_reader:
#             print(row[0])
#             try:
#                 cost_center = CostCenter.objects.get(number=random.randint(0,12))
#                 unity = Unity.objects.get(id=row[0][17])
#                 user = User.objects.get(id=row[0][18])
#                 print("COST CENTER : ", cost_center)
#                 print("UNITY : ", unity)
#                 print("user : ", user)
#                 obj = Employee.objects.create(
#                     identifier=row[0][0],
#                     name=row[0][1],
#                     bio=row[0][2],
#                     admission=row[0][3],
#                     birth_date=row[0][5],
#                     zip_code=row[0][6],
#                     andress=row[0][7],
#                     andress_number=row[0][8],
#                     district=row[0][9],
#                     email=row[0][10],
#                     phone=row[0][11],
#                     cpf=row[0][12],
#                     role=row[0][13],
#                     cost_center=int(cost_center),
#                     gender=row[0][15],
#                     unity=int(unity),
#                     user=int(user))
#                 obj.save()
#             except Employee.DoesNotExist:
#                 print("Objeto não existe.")


# class Migration(migrations.Migration):

#     dependencies = [
#         ('users', '0013_auto_20201112_1914'),
#     ]

#     operations = [
#         migrations.RunPython(insert_unity_models),
#         migrations.RunPython(insert_employee_models),
#     ]
