# Generated by Django 2.2.5 on 2020-11-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201112_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='locomotion',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Transporte Publico', 'Transporte publico'), ('Caminhada a pé', 'Caminhada a pé')], default=1, max_length=60, verbose_name='Locomoção'),
            preserve_default=False,
        ),
    ]
