# Generated by Django 2.2.5 on 2020-10-28 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0011_auto_20201024_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenteeismRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenteeism_days', models.IntegerField(verbose_name='Dias de absenteismo')),
                ('days_month', models.IntegerField(verbose_name='Dias no mês')),
                ('date_register', models.DateTimeField(verbose_name='Mês referente ao calculo')),
                ('absenteeism', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Absenteísmo')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Employee', verbose_name='Funcionário')),
            ],
        ),
    ]
