# Generated by Django 2.2.5 on 2020-10-28 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0002_auto_20201027_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='date_register',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 1, 3, 29, 847202), verbose_name='Mês referente ao calculo'),
        ),
    ]
