# Generated by Django 2.2.5 on 2020-10-30 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0003_auto_20201028_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='date_register',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mês referente ao calculo'),
        ),
    ]
