# Generated by Django 2.2.5 on 2020-11-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0004_auto_20201029_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='absenteeism',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, verbose_name='Absenteísmo'),
        ),
    ]
