# Generated by Django 2.2.5 on 2020-11-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0007_auto_20201113_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='absenteeism',
            field=models.CharField(max_length=5, verbose_name='Absenteeism'),
        ),
    ]
