# Generated by Django 2.2.5 on 2020-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0008_auto_20201113_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='absenteeism',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Absenteísmo'),
        ),
    ]
