# Generated by Django 2.2.5 on 2020-11-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hour', '0009_auto_20201113_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeismrate',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_abis', to='users.Employee', verbose_name='Funcionário'),
        ),
    ]
