# Generated by Django 2.2.5 on 2020-09-12 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200907_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='users.Employee'),
        ),
    ]
