# Generated by Django 2.2.5 on 2020-10-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_periodicexam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicexam',
            options={'verbose_name': 'Exame Periódico', 'verbose_name_plural': 'Exames Periódicos'},
        ),
    ]
