# Generated by Django 2.2.5 on 2020-10-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20201017_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_imc', to='users.Employee'),
        ),
    ]
