# Generated by Django 2.2.5 on 2020-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20201018_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicexam',
            name='final_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data fim'),
        ),
        migrations.AlterField(
            model_name='periodicexam',
            name='initial_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data início'),
        ),
    ]
