# Generated by Django 2.2.5 on 2020-10-22 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20201018_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='weighing_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 0, 58, 6, 600368), editable=False, verbose_name='Data Pesagem'),
        ),
    ]
