# Generated by Django 2.2.5 on 2020-10-24 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20201022_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymassindex',
            name='weighing_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data Pesagem'),
        ),
    ]
