# Generated by Django 2.2.5 on 2020-11-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20201101_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='employee_t',
            new_name='employee',
        ),
    ]
