# Generated by Django 2.2.5 on 2020-08-30 00:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100, verbose_name='Nome da Entidade')),
                ('social_reason', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('contact_person', models.CharField(max_length=30, verbose_name='Pessoa Responsável')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('address', models.CharField(max_length=60, verbose_name='Endereço')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('email', models.EmailField(error_messages={'required': 'Porfavor digite seu e-mail.', 'unique': 'Já existe esse e-mail cadastrado.'}, max_length=70, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100, verbose_name='Nome Treinamento')),
                ('category', models.CharField(max_length=25, verbose_name='Categoria')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('required', models.CharField(max_length=50, verbose_name='Requisito')),
                ('resource', models.CharField(max_length=50, verbose_name='Recursos')),
                ('training_type', models.CharField(max_length=50, verbose_name='Tipo de Treinamento')),
                ('local', models.CharField(max_length=50, verbose_name='Local')),
                ('workload', models.CharField(max_length=5, verbose_name='Carga Horária')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('register_instructor', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)], verbose_name='Registro Instrutor')),
                ('instructor_name', models.CharField(max_length=100, verbose_name='Nome Instrutor')),
                ('instructor_photo', models.ImageField(blank=True, null=True, upload_to='photos_instructor', verbose_name='Foto do Instrutor')),
                ('training', models.ManyToManyField(to='training.Training')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=80, verbose_name='Nome do Evento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('event_date', models.DateTimeField(blank=True, verbose_name='Data Consulta')),
                ('present_list', models.FileField(default='', upload_to='present_list', verbose_name='Lista de Presença')),
                ('entity', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='training.Entity')),
                ('instructor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='training.Instructor')),
                ('training', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='event', to='training.Training')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
