# Generated by Django 2.2.5 on 2020-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200921_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
    ]
